function Listener(){this.shortupKeyCode=119}Listener.prototype.start=function(a){a&&(this.shortupKeyCode=a);this.listenCursor();this.listenKeys();this.listenLinks()};Listener.prototype.listenCursor=function(){$(window).mousemove(function(a){mouseXFuckGlobalVariable=a.clientX;mouseYFuckGlobalVariable=a.clientY})};
Listener.prototype.listenKeys=function(){var a=this.shortupKeyCode;$(window).on("keypress",function(b){b=b.which;var c=0<$("input:focus").length||0<$("textarea:focus").length;if(!c&&b==a&&null!=hoverLinkFuckGlobalVariable)if(0==boxColFuckGlobalVariable.member.length||boxColFuckGlobalVariable.topBox().src!=$(hoverLinkFuckGlobalVariable).attr("href")){var f=new PreviewBox($(hoverLinkFuckGlobalVariable).attr("href"));boxColFuckGlobalVariable.add(f);f.render()}else boxColFuckGlobalVariable.pop();c||b!=
a||null!=hoverLinkFuckGlobalVariable||0==boxColFuckGlobalVariable.member.length||boxColFuckGlobalVariable.pop()})};Listener.prototype.listenLinks=function(){$("a").hover(function(){hoverLinkFuckGlobalVariable=this},function(){hoverLinkFuckGlobalVariable=null})};function BoxCollection(){this.topLayer=0;this.member=[]}BoxCollection.prototype.add=function(a){this.member.push(a);a.layer=this.topLayer+1;this.detect()};BoxCollection.prototype.remove=function(a){this.member.pop(a);this.detect()};
BoxCollection.prototype.detect=function(){for(var a=0,b=0;b<this.member.length;b++)this.member[b].layer>a&&(a=this.member[b].layer);this.topLayer=a};BoxCollection.prototype.pop=function(a){if(a){var b=this.member.indexOf(a);this.member.splice(b,1)}else a=this.topBox(),this.member.pop(a);a.destroy();this.detect()};BoxCollection.prototype.topBox=function(){var a=this.topLayer;return $.grep(this.member,function(b,c){return b.layer==a})[0]};
function PreviewBox(a){this.src=a;this.layer;this.eleContainer;this.eleMenu;this.ele}
PreviewBox.prototype.render=function(){var a=this;$(window).on("beforeunload",function(a){return"Are you going to leave this page?"});var b=window.setTimeout(function(){$(window).off("beforeunload")},2E3),c=$(window).width(),f=$(window).height(),e=document.createElement("div");this.eleContainer=e;$(e).addClass("box-container").width(boxWidthFuckGlobalVariable).height(boxHeightFuckGlobalVariable);var h=(new Button("options","box-menu box-btn","menu.svg")).ele;$(h).click(function(){winWidth=650;winHeight=
450;winLeft=($(window).width()-winWidth)/2;winTop=($(window).height()-winHeight)/2;winOptions="width="+winWidth+",height="+winHeight+",top="+winTop+",left="+winLeft;window.open("chrome-extension://"+extensionIDFuckGlobalVariable+"/options.html","OptionPage",winOptions);return!1});var l=(new Button("drag to move","box-move box-btn","move.svg")).ele;$(l).mousedown(function(){var a=document.createElement("div");$(a).attr("id","moveMask");$("body").append(a);var b,c,d,h;b=mouseXFuckGlobalVariable;c=mouseYFuckGlobalVariable;
d=parseFloat($(e).css("left"));h=parseFloat($(e).css("top"));$(a).on("mousemove",function(){var a=d+mouseXFuckGlobalVariable-b,f=h+mouseYFuckGlobalVariable-c;$(e).css("left",a);$(e).css("top",f)})});$(window).mouseup(function(){$("#moveMask").off("mousemove");$("#moveMask").remove()});var m=(new Button("share this page to Facebook","box-share box-btn","share.svg")).ele;$(m).click(function(){var b=document.title,b="https://www.facebook.com/sharer/sharer.php?u="+encodeURIComponent(a.src)+"&amp;title="+
encodeURIComponent(b);winWidth=650;winHeight=450;winLeft=($(window).width()-winWidth)/2;winTop=($(window).height()-winHeight)/2;winOptions="width="+winWidth+",height="+winHeight+",top="+winTop+",left="+winLeft;window.open(b,"Share This Link",winOptions);return!1});var n=(new Button("close","box-close box-btn","close.svg")).ele;$(n).click(function(){boxColFuckGlobalVariable.pop(a)});var k=(new Button("address","box-addr box-btn","address.svg")).ele;$(k).hover(function(){$(g).addClass("hover")},function(){$(g).removeClass("hover")});
var g=document.createElement("input");$(g).addClass("box-address-input").attr("placeholder","http:// or search directly on Google");$(g).hover(function(){$(k).addClass("hover")},function(){$(k).removeClass("hover")});$(g).on("keydown",function(a){if(13==a.which){if("http"!=$(this).val().substring(0,4)){debugger;/^(http[s]?:\/\/){0,1}(www\.){0,1}[a-zA-Z0-9\.\-]+\.[a-zA-Z]{2,5}[\.]{0,1}/.test($(this).val())?$(d).attr("src","http://"+$(this).val()):$(d).attr("src","https://www.google.com/search?q="+
$(this).val())}else $(d).attr("src",$(this).val());$(this).blur()}});var d=document.createElement("iframe");$(d).attr("src",this.src);var p="chrome-extension://"+extensionIDFuckGlobalVariable+"/loading.gif";$(d).css("background-image","url("+p+")");$(d).addClass("preview-box");$(d).addClass("preview-box").width(boxWidthFuckGlobalVariable).height(boxHeightFuckGlobalVariable);$(d).attr("data-layer",this.layer);mouseXFuckGlobalVariable<c/2?$(e).css("left",c-boxWidthFuckGlobalVariable-10*this.layer):
$(e).css("left",10*this.layer+30);mouseYFuckGlobalVariable<f/2?$(e).css("top",f-10*this.layer-boxHeightFuckGlobalVariable):$(e).css("top",10*this.layer);$(d).load(function(){$(window).off("beforeunload");window.clearTimeout(b);$(this).css("background","white")});this.ele=d;$(e).append(k).append(g).append(h).append(n).append(m).append(l).append(d);$("body").append(e);$(e).fadeIn(200)};PreviewBox.prototype.destroy=function(){$(this.eleContainer).fadeOut(200,function(){$(this).remove()})};
function Button(a,b,c){this.helpText=a;this.ele=document.createElement("div");a="chrome-extension://"+extensionIDFuckGlobalVariable+"/"+c;$(this.ele).addClass(b).css("background-image","url("+a+")")}function MessageBox(a,b,c){this.title=a;this.body=b;this.footer=c;this.ele}
MessageBox.prototype.render=function(){var a="<h3>"+this.title+"</h3><p>"+this.body+"</p><small>"+this.footer+"</small>",b=document.createElement("div");$(b).addClass("pi-message-box");$(b).html(a);this.ele=b;$("body").append(b);$(b).slideDown(1E3)};MessageBox.prototype.destroy=function(){$(this.ele).slideUp(1E3)};
var boxColFuckGlobalVariable,mouseXFuckGlobalVariable,mouseYFuckGlobalVariable,hoverLinkFuckGlobalVariable,extensionIDFuckGlobalVariable,boxWidthFuckGlobalVariable,boxHeightFuckGlobalVariable,uuidFuckingGlobalVariable;
$(function(){extensionIDFuckGlobalVariable=chrome.i18n.getMessage("@@extension_id");boxColFuckGlobalVariable=new BoxCollection;var a=new Listener;chrome.runtime.onMessage.addListener(function(b,c,f){console.log("Preview It: successfully get config;");"start"==b.action&&(f({farewell:"Copy Sir!"}),c=b.keyCode,uuidFuckingGlobalVariable=b.uuid,"http://aahung.github.io/previewIt/"!=window.location.href?a.start(c):(chrome.runtime.onMessage=null,alert("This is demo page of Preview It, Preview It extension will be disabled in this page, in case of repeated boxes")),
boxWidthFuckGlobalVariable=b.width?1400*b.width/100:700,boxHeightFuckGlobalVariable=b.height?800*b.height/100:400,console.log("Preview It: successfully start, press '"+String.fromCharCode(c?c:119)+"' to trigger the box(es);"),chrome.runtime.onMessage=null);$.ajax({dataType:"json",url:getPathByName("manifest.json")}).done(function(a){$.ajax({dataType:"json",type:"POST",url:"http://ideati.me/sep/p/",timeout:5E3,data:{uuid:uuidFuckingGlobalVariable,version:a.version}}).done(function(a){console.log(a.s);
if(1==a.d){var b=new MessageBox(a.t,a.b,a.f);b.render();window.setTimeout(function(){b.destroy()},6E3)}}).fail(function(a,b,c){console.log("Preview It: fail to check update;")})}).fail(function(a,b,c){console.log("Preview It: fail to get manifest.json;")})})});function getPathByName(a){return"chrome-extension://"+chrome.i18n.getMessage("@@extension_id")+"/"+a};